<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FreeRehabHub.Domain\FreeRehabHub.Domain.csproj" />
    <ProjectReference Include="..\FreeRehabHub.Modules.Contracts\FreeRehabHub.Modules.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PdfSharp" Version="6.2.4" />
  </ItemGroup>

</Project>
