# MediaPipe PoseLandmarker'ın döndürdüğü 33 landmark, index sırasına göre. C# tarafındaki
# FreeRehabHub.Modules.Contracts.PoseLandmarkType enum'uyla index-eş (bkz. PoseLandmarkType.cs) —
# buradaki camelCase isimler JsonNamingPolicy.CamelCase'in enum adlarını çevireceği isimlerle birebir.
LANDMARK_NAMES = [
    "nose",
    "leftEyeInner",
    "leftEye",
    "leftEyeOuter",
    "rightEyeInner",
    "rightEye",
    "rightEyeOuter",
    "leftEar",
    "rightEar",
    "mouthLeft",
    "mouthRight",
    "leftShoulder",
    "rightShoulder",
    "leftElbow",
    "rightElbow",
    "leftWrist",
    "rightWrist",
    "leftPinky",
    "rightPinky",
    "leftIndex",
    "rightIndex",
    "leftThumb",
    "rightThumb",
    "leftHip",
    "rightHip",
    "leftKnee",
    "rightKnee",
    "leftAnkle",
    "rightAnkle",
    "leftHeel",
    "rightHeel",
    "leftFootIndex",
    "rightFootIndex",
]
